### PR TITLE
#277 fix: implemented content caching in SourceMapGeneratorV3

### LINKED ISSUE #277: OutOfMemory when compiling heavy sources
I'm trying to compile ~84 .less files (~700KB total) via Grails less asset plugin and I'm getting OutOfMemory error on 1Gb heap.
Quick heap dump analysis shows that source files' content is duplicated for each SourceMapGeneratorV3.Mapping class
Screenshot
I beleive some kind of caching should be implemented there to avoid content duplication, but I'm not sure where it should be done - in the grails plugin (it uses custom LessSource implementation) or inside less4j

### PR DESCRIPTION
**Pull request by alex-bel**
This fixes #277

### CODE REVIEW

File: src/main/java/com/github/sommeri/less4j/core/output/SourceMapBuilder.java [hunk 1]
```diff
@@ -24,6 +26,7 @@
   private final SourceMapGenerator generator;
   private final LessCompiler.SourceMapConfiguration configuration;
   private final Collection<LessSource> additionalSourceFiles;
+  private final Map<LessSource, String> cachedContent;
```
Comment (martin-g) [inline src/main/java/com/github/sommeri/less4j/core/output/SourceMapBuilder.java]: I think it would be better to use ConcurrentMap with `putIfAbsent()` instead of `put()`.

Comment (alex-bel) [inline src/main/java/com/github/sommeri/less4j/core/output/SourceMapBuilder.java]: Maybe I missed something, but it seems that Less compilation process in less4j is single threaded. If it is actually single threaded, why should we use concurrent stuff there?

**Comment by SomMeri** [comment]
Thanks a lot for finding this and also the pull request.
